Feature/local storage
MathiSans/capstone_mood-tracker pull request #12
Opened 2024-03-04 11:09 UTC by NikCrmr

2024-03-04 14:18 UTC, MerleMak requested changes
Very long review 😮‍💨
But here you go! I left you some structural feedback and some comments and console.log that you forgot :P 
Remember to always delete them before committing your code. 

One thing that i quite important:
This PR has almost nothing to do with Local Storage. The local storage her eis like one line of code.

You did EVERYTHING here, so in the future try to seperate all these tasks into different tickets and you youll be good to go! :)


Nice job on the code otherwise! I know it seems like a lot of comments, but it is absolutely normal with this many lines of code. 

Keep it going guys! Your are on a good way 👌🏻

2024-03-04 14:18 UTC, MerleMak commented on components/TextBox/TextBox.js
> +}
just import Textbox directly to the form.js

2024-03-04 14:18 UTC, MerleMak commented on pages/_app.js
> +  // const [allEntries, setAllEntries] = useState([]);
```suggestion
```

2024-03-04 14:18 UTC, MerleMak commented on utils/onSubmit.js
> +}
You can delete this. 
You have already implemented this code in the _app.js, so I don't think you are using it anywhere

2024-03-04 14:18 UTC, MerleMak commented on pages/flow.js
> +      </StyledEntryList> */}
```suggestion
```
always delete commented out code before the commit!

2024-03-04 14:18 UTC, MerleMak commented on pages/flow.js
> +// `;
```suggestion
```
!

2024-03-04 14:18 UTC, MerleMak commented on pages/_app.js
> +    console.log([...allEntries, submittedForm]);
```suggestion
```

2024-03-04 14:18 UTC, MerleMak commented on pages/_app.js
> +    const submittedForm = {
beautiful!!

2024-03-04 14:18 UTC, MerleMak commented on data.json
> +]
i think you can delete this?

2024-03-05 11:25 UTC, Ramin-faqyri commented on components/EntryList/EntryList.js
> +}
We don't have a entry component yet to display the details. We resolved the issue like you suggested in the previous comment.

2024-03-05 11:38 UTC, MerleMak approved these changes

2024-03-05 11:44 UTC, merged